# Generated by Django 3.0.2 on 2020-01-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceoid', models.CharField(max_length=50)),
                ('ceopassword', models.CharField(max_length=50)),
                ('ceoname', models.CharField(max_length=10)),
                ('cafe', models.CharField(max_length=50)),
                ('cafeaddress', models.TextField()),
                ('start_time', models.TimeField(verbose_name='date published')),
                ('end_time', models.TimeField(verbose_name='date published')),
            ],
        ),
    ]
