# Generated by Django 2.2.7 on 2020-01-16 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffcapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cafe',
        ),
        migrations.AlterField(
            model_name='image',
            name='image1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image1', to='ffcapp.Cafe'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image2', to='ffcapp.Cafe'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image3', to='ffcapp.Cafe'),
        ),
    ]
