# Generated by Django 3.0.2 on 2020-01-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceo',
            name='end_time',
            field=models.TimeField(verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='start_time',
            field=models.TimeField(verbose_name='start_time'),
        ),
    ]
