# Generated by Django 2.2.7 on 2020-01-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='end_time',
            field=models.TimeField(default='', verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='holiday',
            field=models.CharField(default='', max_length=27),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='phonenumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='socket',
            field=models.CharField(choices=[('yes', '있음'), ('no', '없음'), ('soso', '적당히 있음')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='start_time',
            field=models.TimeField(default='', verbose_name='start_time'),
        ),
    ]
