# Generated by Django 3.0.2 on 2020-01-09 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffcapp', '0002_auto_20200109_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ceo',
        ),
    ]
