# Generated by Django 2.2.7 on 2020-01-16 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffcapp', '0002_auto_20200116_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='ffcapp.Cafe'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
