# Generated by Django 2.2.7 on 2020-01-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcapp', '0002_auto_20200112_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='holiday',
            field=models.CharField(max_length=27, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='menu',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='phonenumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='socket',
            field=models.CharField(choices=[('yes', '있음'), ('no', '없음'), ('soso', '적당히 있음')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='start_time'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
