# Generated by Django 3.0.2 on 2020-01-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ffcapp', '0003_delete_ceo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phonenumber', models.CharField(max_length=20)),
                ('start_time', models.TimeField(verbose_name='start_time')),
                ('end_time', models.TimeField(verbose_name='end_time')),
                ('holiday', models.CharField(max_length=27)),
                ('content', models.TextField()),
                ('socket', models.CharField(choices=[('yes', '있음'), ('no', '없음'), ('soso', '적당히 있음')], max_length=4)),
            ],
        ),
    ]
