# Generated by Django 2.2.7 on 2020-01-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcapp', '0003_auto_20200112_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='image',
            name='image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
