# Generated by Django 2.2.7 on 2020-01-16 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffcapp', '0003_auto_20200116_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='cafe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cafe', to='ffcapp.Cafe'),
        ),
    ]
