# Generated by Django 2.2.7 on 2020-01-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcapp', '0004_cafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='cafeimage',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='menu',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
