# Generated by Django 2.2.7 on 2020-01-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcapp', '0006_auto_20200116_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='mainimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='menu',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
