# Generated by Django 2.2.7 on 2020-01-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcapp', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=True, help_text='방문했던 카페는 어떠셨나요? 점수를 입력해주세요(1~5점)'),
        ),
    ]
