# Generated by Django 2.2.7 on 2020-01-16 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ffcapp', '0009_comment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.IntegerField(blank=True, default=True, help_text='방문했던 카페는 어떠셨나요? 점수를 입력해주세요(1~5점)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
