# Generated by Django 2.2.7 on 2020-01-16 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffcapp', '0011_auto_20200116_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=True, help_text='방문했던 카페는 어떠셨나요? 점수를 입력해주세요(1~5점)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
