# Generated by Django 3.0.2 on 2020-01-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ceo',
            field=models.BooleanField(default=True),
        ),
    ]
