# Generated by Django 3.0.2 on 2020-01-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200117_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ceo',
            field=models.BooleanField(default=False),
        ),
    ]
